# Generated by Django 4.1 on 2022-10-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="admin", new_name="administrator",
        ),
    ]
