# Generated by Django 2.1 on 2018-11-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('duration', models.TimeField()),
                ('small_image', models.CharField(max_length=500)),
                ('big_image', models.CharField(max_length=500)),
            ],
        ),
    ]
